# Settings that apply to the Controller bot instance
[SynthOS]
AdminID = "discord-user-id-number"
LogLevel = "trace"

[SynthOS.Controller]
Token = "discord-app-token"

[Database]
DBDriver = "sqlite3"
DSN = "synthos.sqlite"
